AllCops:
  RunRailsCops: true
  Exclude:
    - db/**
    - bin/rails
    - bin/rake
    - config/deploy.rb

Lint/AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/TrailingComma:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - test/**/*

Metrics/LineLength:
  Max: 120
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false
